build_mta:
    image: test-docker-repo.docker.repositories.sap.ondemand.com/mta-build-deploy:latest
    stage: build
    script:
      - sed -e 's/webshop/webshopgitlab/g' -i mta.yaml
      - sed -e 's/espm/espmgitlab/g' -i mta.yaml
      - export PATH=./node_modules/.bin:${PATH}
      - mta.sh --mtar result.mtar --build-target=NEO build
    artifacts:
        paths:
          - result.mtar

deploy_neo:
    image: test-docker-repo.docker.repositories.sap.ondemand.com/mta-build-deploy:latest
    stage: deploy
    dependencies:
        - build_mta
    script:
      - neo.sh deploy-mta --host "${NEO_DEPLOY_HOST}" --account "${NEO_DEPLOY_ACCOUNT}" --synchronous --user "${NEO_DEPLOY_USER}" --password "${NEO_DEPLOY_PASSWORD}" --source "result.mtar"
      - echo "Application running at https://webshopgitlab-${NEO_DEPLOY_ACCOUNT}.dispatcher.${NEO_DEPLOY_HOST}/index.html"
